// Mocks generated by Mockito 5.4.6 from annotations
// in flutter_repsync_app/test/providers/data_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_repsync_app/models/band.dart' as _i6;
import 'package:flutter_repsync_app/models/setlist.dart' as _i8;
import 'package:flutter_repsync_app/models/song.dart' as _i4;
import 'package:flutter_repsync_app/repositories/band_repository.dart' as _i5;
import 'package:flutter_repsync_app/repositories/setlist_repository.dart'
    as _i7;
import 'package:flutter_repsync_app/repositories/song_repository.dart' as _i2;
import 'package:flutter_repsync_app/services/cache_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SongRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongRepository extends _i1.Mock implements _i2.SongRepository {
  MockSongRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSong(_i4.Song? song, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#saveSong, [song], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSong(String? songId, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSong, [songId], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSong(_i4.Song? song, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#updateSong, [song], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Song>> watchSongs(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchSongs, [uid]),
            returnValue: _i3.Stream<List<_i4.Song>>.empty(),
          )
          as _i3.Stream<List<_i4.Song>>);

  @override
  _i3.Future<void> addSongToBand({
    required _i4.Song? song,
    required String? bandId,
    String? contributorId,
    String? contributorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSongToBand, [], {
              #song: song,
              #bandId: bandId,
              #contributorId: contributorId,
              #contributorName: contributorName,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addSongToBandById(String? songId, String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#addSongToBandById, [songId, bandId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveBandSong(_i4.Song? song, String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#saveBandSong, [song, bandId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Song>> watchBandSongs(String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBandSongs, [bandId]),
            returnValue: _i3.Stream<List<_i4.Song>>.empty(),
          )
          as _i3.Stream<List<_i4.Song>>);

  @override
  _i3.Future<void> deleteBandSong(String? bandId, String? songId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBandSong, [bandId, songId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBandSong(_i4.Song? song, String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#updateBandSong, [song, bandId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [BandRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBandRepository extends _i1.Mock implements _i5.BandRepository {
  MockBandRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveBand(_i6.Band? band, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#saveBand, [band], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBand(String? bandId, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBand, [bandId], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i6.Band>> watchBands(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchBands, [uid]),
            returnValue: _i3.Stream<List<_i6.Band>>.empty(),
          )
          as _i3.Stream<List<_i6.Band>>);

  @override
  _i3.Future<void> saveBandToGlobal(_i6.Band? band) =>
      (super.noSuchMethod(
            Invocation.method(#saveBandToGlobal, [band]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i6.Band?> getBandByInviteCode(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#getBandByInviteCode, [code]),
            returnValue: _i3.Future<_i6.Band?>.value(),
          )
          as _i3.Future<_i6.Band?>);

  @override
  _i3.Future<bool> isInviteCodeTaken(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#isInviteCodeTaken, [code]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> addUserToBand(String? bandId, {String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#addUserToBand, [bandId], {#userId: userId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> removeUserFromBand(String? bandId, {String? userId}) =>
      (super.noSuchMethod(
            Invocation.method(#removeUserFromBand, [bandId], {#userId: userId}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [SetlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSetlistRepository extends _i1.Mock implements _i7.SetlistRepository {
  MockSetlistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSetlist(_i8.Setlist? setlist, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#saveSetlist, [setlist], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSetlist(String? setlistId, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSetlist, [setlistId], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i8.Setlist>> watchSetlists(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchSetlists, [uid]),
            returnValue: _i3.Stream<List<_i8.Setlist>>.empty(),
          )
          as _i3.Stream<List<_i8.Setlist>>);
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i9.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheSongs(String? uid, List<_i4.Song>? songs) =>
      (super.noSuchMethod(
            Invocation.method(#cacheSongs, [uid, songs]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Song>> getCachedSongs(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSongs, [uid]),
            returnValue: _i3.Future<List<_i4.Song>>.value(<_i4.Song>[]),
          )
          as _i3.Future<List<_i4.Song>>);

  @override
  _i3.Future<DateTime?> getSongsCacheTimestamp(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getSongsCacheTimestamp, [uid]),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> clearSongsCache(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#clearSongsCache, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cacheBands(String? uid, List<_i6.Band>? bands) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBands, [uid, bands]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i6.Band>> getCachedBands(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedBands, [uid]),
            returnValue: _i3.Future<List<_i6.Band>>.value(<_i6.Band>[]),
          )
          as _i3.Future<List<_i6.Band>>);

  @override
  _i3.Future<DateTime?> getBandsCacheTimestamp(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getBandsCacheTimestamp, [uid]),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> clearBandsCache(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#clearBandsCache, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cacheSetlists(String? uid, List<_i8.Setlist>? setlists) =>
      (super.noSuchMethod(
            Invocation.method(#cacheSetlists, [uid, setlists]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.Setlist>> getCachedSetlists(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedSetlists, [uid]),
            returnValue: _i3.Future<List<_i8.Setlist>>.value(<_i8.Setlist>[]),
          )
          as _i3.Future<List<_i8.Setlist>>);

  @override
  _i3.Future<DateTime?> getSetlistsCacheTimestamp(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getSetlistsCacheTimestamp, [uid]),
            returnValue: _i3.Future<DateTime?>.value(),
          )
          as _i3.Future<DateTime?>);

  @override
  _i3.Future<void> clearSetlistsCache(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#clearSetlistsCache, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cacheBandSongs(String? bandId, List<_i4.Song>? songs) =>
      (super.noSuchMethod(
            Invocation.method(#cacheBandSongs, [bandId, songs]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Song>> getCachedBandSongs(String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedBandSongs, [bandId]),
            returnValue: _i3.Future<List<_i4.Song>>.value(<_i4.Song>[]),
          )
          as _i3.Future<List<_i4.Song>>);

  @override
  _i3.Future<void> clearBandSongsCache(String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#clearBandSongsCache, [bandId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllUserCache(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#clearAllUserCache, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> hasCache(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#hasCache, [uid]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
