// Mocks generated by Mockito 5.4.6 from annotations
// in flowgroove/test/screens/metronome_tempo_autosave_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowgroove/models/song.dart' as _i4;
import 'package:flowgroove/repositories/song_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SongRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSongRepository extends _i1.Mock implements _i2.SongRepository {
  MockSongRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveSong(_i4.Song? song, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#saveSong, [song], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteSong(String? songId, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSong, [songId], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateSong(_i4.Song? song, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#updateSong, [song], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> revertSongToCanonical(_i4.Song? song, {String? uid}) =>
      (super.noSuchMethod(
            Invocation.method(#revertSongToCanonical, [song], {#uid: uid}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Song>> watchSongs(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchSongs, [uid]),
            returnValue: _i3.Stream<List<_i4.Song>>.empty(),
          )
          as _i3.Stream<List<_i4.Song>>);

  @override
  _i3.Future<void> addSongToBand({
    required _i4.Song? song,
    required String? bandId,
    String? contributorId,
    String? contributorName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addSongToBand, [], {
              #song: song,
              #bandId: bandId,
              #contributorId: contributorId,
              #contributorName: contributorName,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> addSongToBandById(String? songId, String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#addSongToBandById, [songId, bandId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveBandSong(_i4.Song? song, String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#saveBandSong, [song, bandId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Song>> watchBandSongs(String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBandSongs, [bandId]),
            returnValue: _i3.Stream<List<_i4.Song>>.empty(),
          )
          as _i3.Stream<List<_i4.Song>>);

  @override
  _i3.Future<void> deleteBandSong(String? bandId, String? songId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBandSong, [bandId, songId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBandSong(_i4.Song? song, String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#updateBandSong, [song, bandId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> revertBandSongToCanonical(_i4.Song? song, String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#revertBandSongToCanonical, [song, bandId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.Song>> getSongs(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getSongs, [uid]),
            returnValue: _i3.Future<List<_i4.Song>>.value(<_i4.Song>[]),
          )
          as _i3.Future<List<_i4.Song>>);

  @override
  _i3.Future<List<_i4.Song>> getBandSongs(String? bandId) =>
      (super.noSuchMethod(
            Invocation.method(#getBandSongs, [bandId]),
            returnValue: _i3.Future<List<_i4.Song>>.value(<_i4.Song>[]),
          )
          as _i3.Future<List<_i4.Song>>);
}
