#!/bin/bash
# Session End Script - FlowGroove Project
# Usage: ./scripts/session-end.sh "Session description"

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
CODEX_DIR="$PROJECT_ROOT/.codex"
SESSION_DIR="$CODEX_DIR/sessions"
EXPORTS_DIR="$SESSION_DIR/exports"
STATUS_FILE="$CODEX_DIR/STATUS.md"
HANDOFF_FILE="$CODEX_DIR/HANDOFF.md"
DECISIONS_FILE="$CODEX_DIR/DECISIONS.md"
DATE_STAMP=$(date +%Y-%m-%d)
TIMESTAMP=$(date +%Y-%m-%dT%H-%M-%S)

mkdir -p "$SESSION_DIR" "$EXPORTS_DIR"

SESSION_DESC="${1:-Session $(date +%Y-%m-%d)}"

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║              Ending Codex Session                         ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "📝 Session: $SESSION_DESC"
echo "📅 Date: $DATE_STAMP"
echo ""

echo "📤 Step 1: Reserving export location..."
EXPORT_FILE="$EXPORTS_DIR/${DATE_STAMP}_session-${TIMESTAMP}.md"
echo "   Export location: $EXPORT_FILE"
echo "   ℹ️  Manual step: save any chat export here if you need a durable transcript"
echo ""

echo "📝 Step 2: Saving session state..."
STATE_FILE="$SESSION_DIR/SESSION_STATE.md"

cat > "$STATE_FILE" << EOF
# Session State - $DATE_STAMP

**Session Ended:** $(date +"%Y-%m-%d %H:%M:%S")
**Session Description:** $SESSION_DESC

## Current Branch
$(git branch --show-current 2>/dev/null || echo "Unknown")

## Recent Commits
$(git log --oneline -5 2>/dev/null || echo "Unable to get git log")

## Files Modified This Session
$(git status --short 2>/dev/null | head -20 || echo "Unable to get git status")

## Active Control Plane
- Status file: .codex/STATUS.md
- Handoff file: .codex/HANDOFF.md
- Decisions file: .codex/DECISIONS.md

## Notes
Add any important context for the next session here.

---
*Generated by session-end.sh*
EOF

echo "   ✅ Session state saved to: $STATE_FILE"
echo ""

echo "📋 Step 3: Creating next session snapshot..."
NEXT_SESSION_FILE="$SESSION_DIR/NEXT_SESSION.md"

cat > "$NEXT_SESSION_FILE" << EOF
# Next Session Context

**Previous Session:** $DATE_STAMP
**Previous Session Description:** $SESSION_DESC

## Carry-Over Tasks
- [ ] 

## Current Focus
- 

## Important Context
- Review .codex/STATUS.md
- Review .codex/HANDOFF.md
- Review .codex/DECISIONS.md if decisions changed

## Branch Status
Current branch: $(git branch --show-current 2>/dev/null || echo "Unknown")
Last commit: $(git log -1 --oneline 2>/dev/null || echo "Unknown")

## Files to Review
- .codex/STATUS.md
- .codex/HANDOFF.md
- .codex/MEMORY.md

## Agents to Consider
- [ ] mr-senior-developer
- [ ] mr-tester
- [ ] mr-cleaner
- [ ] mr-architect
- [ ] Other: 

---
*Generated by session-end.sh - Review before starting next session*
EOF

echo "   ✅ Next session context saved to: $NEXT_SESSION_FILE"
echo ""

echo "🧹 Step 4: Cleaning temporary files..."
CLEANED=0
find "$PROJECT_ROOT" -name "*.bak" -type f -delete 2>/dev/null && CLEANED=1
find "$PROJECT_ROOT" -name "*.tmp" -type f -delete 2>/dev/null && CLEANED=1
find "$PROJECT_ROOT" -name ".DS_Store" -type f -delete 2>/dev/null && CLEANED=1

if [ "$CLEANED" -eq 1 ]; then
    echo "   ✅ Temporary files cleaned"
else
    echo "   ℹ️  No temporary files to clean"
fi
echo ""

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║              ✅ Session Ended Successfully                ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "📊 Summary:"
echo "   Session: $SESSION_DESC"
echo "   Date: $DATE_STAMP"
echo "   Branch: $(git branch --show-current 2>/dev/null || echo "Unknown")"
echo ""
echo "📁 Generated Files:"
echo "   - $STATE_FILE"
echo "   - $NEXT_SESSION_FILE"
echo ""
echo "📝 Before you stop:"
echo "   1. Update $STATUS_FILE"
echo "   2. Update $HANDOFF_FILE"
echo "   3. Update $DECISIONS_FILE if a durable decision was made"
echo "   4. Start next session with: ./scripts/session-start.sh"
echo ""

read -r -p "🔧 Commit session artifacts now? (y/N): " -n 1 -r
echo ""
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "📝 Committing session artifacts..."
    git add "$STATE_FILE" "$NEXT_SESSION_FILE" 2>/dev/null || true
    git commit -m "chore: End session - $SESSION_DESC" || echo "   ℹ️  No changes to commit"
    echo "   ✅ Session artifacts committed"
fi
echo ""
