import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../models/setlist.dart';
import '../../models/song.dart';

/// PDF layout for a setlist export. `lyricsChords` is reserved for a future
/// per-song chords+lyrics layout (not built yet).
enum SetlistPdfLayout { detailed, compact }

class PdfService {
  static Future<void> exportSetlist(
    Setlist setlist,
    List<Song> songs, {
    SetlistPdfLayout layout = SetlistPdfLayout.detailed,
  }) async {
    final pdf = pw.Document();

    // Load font that supports Cyrillic characters (Roboto)
    final font = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();

    final songWidgets = layout == SetlistPdfLayout.compact
        ? _compactRows(songs, font, fontBold)
        : _detailedRows(songs, font, fontBold);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              setlist.name,
              style: pw.TextStyle(
                font: fontBold,
                fontSize: 24,
              ),
            ),
            if (setlist.description != null) ...[
              pw.SizedBox(height: 4),
              pw.Text(
                setlist.description!,
                style: pw.TextStyle(
                  font: font,
                  fontSize: 12,
                  color: PdfColor.fromHex('757575'),
                ),
              ),
            ],
            if (setlist.eventLocation != null) ...[
              pw.SizedBox(height: 8),
              pw.Row(
                children: [
                  pw.Text(
                    '📍 ${setlist.eventLocation}',
                    style: pw.TextStyle(
                      font: font,
                      fontSize: 10,
                    ),
                  ),
                ],
              ),
            ],
            pw.SizedBox(height: 20),
            pw.Divider(color: PdfColor.fromHex('E0E0E0')),
            pw.SizedBox(height: 20),
          ],
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              '${songs.length} songs',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColor.fromHex('757575'),
              ),
            ),
            pw.Text(
              'Generated by FlowGroove',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColor.fromHex('757575'),
              ),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColor.fromHex('757575'),
              ),
            ),
          ],
        ),
        build: (context) => songWidgets,
      ),
    );

    final suffix = layout == SetlistPdfLayout.compact ? '_compact' : '';
    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: '${setlist.name.replaceAll(' ', '_')}_setlist$suffix.pdf',
    );
  }

  /// Boxed card per song, one row each (original layout).
  static List<pw.Widget> _detailedRows(
    List<Song> songs,
    pw.Font font,
    pw.Font fontBold,
  ) {
    final widgets = <pw.Widget>[];
    for (int i = 0; i < songs.length; i++) {
      final song = songs[i];
      widgets.add(
        pw.Container(
          margin: const pw.EdgeInsets.only(bottom: 12),
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColor.fromHex('E0E0E0')),
            borderRadius: pw.BorderRadius.circular(8),
          ),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                width: 30,
                height: 30,
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('E3F2FD'),
                  shape: pw.BoxShape.circle,
                ),
                child: pw.Center(
                  child: pw.Text(
                    '${i + 1}',
                    style: pw.TextStyle(
                      font: fontBold,
                      color: PdfColor.fromHex('0D47A1'),
                    ),
                  ),
                ),
              ),
              pw.SizedBox(width: 12),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      song.title,
                      style: pw.TextStyle(
                        font: fontBold,
                        fontSize: 14,
                      ),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      song.artist,
                      style: pw.TextStyle(
                        font: font,
                        fontSize: 12,
                        color: PdfColor.fromHex('B0B0B0'),
                      ),
                    ),
                  ],
                ),
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  if (song.ourKey != null)
                    pw.Container(
                      padding: const pw.EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 4,
                      ),
                      decoration: pw.BoxDecoration(
                        color: PdfColor.fromHex('E8F5E9'),
                        borderRadius: pw.BorderRadius.circular(4),
                      ),
                      child: pw.Text(
                        song.ourKey!,
                        style: pw.TextStyle(
                          font: fontBold,
                          color: PdfColor.fromHex('1B5E20'),
                        ),
                      ),
                    ),
                  if (song.ourBPM != null) ...[
                    pw.SizedBox(height: 4),
                    pw.Text(
                      '${song.ourBPM} BPM',
                      style: pw.TextStyle(
                        font: fontBold,
                        fontSize: 12,
                        color: PdfColor.fromHex('E65100'),
                      ),
                    ),
                  ],
                ],
              ),
            ],
          ),
        ),
      );
    }
    return widgets;
  }

  /// One dense line per song so a whole setlist fits on a single list.
  static List<pw.Widget> _compactRows(
    List<Song> songs,
    pw.Font font,
    pw.Font fontBold,
  ) {
    final widgets = <pw.Widget>[];
    for (int i = 0; i < songs.length; i++) {
      final song = songs[i];
      final meta = <String>[
        if (song.ourKey != null) song.ourKey!,
        if (song.ourBPM != null) '${song.ourBPM} BPM',
      ].join('  ·  ');
      widgets.add(
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 3),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(
                width: 22,
                child: pw.Text(
                  '${i + 1}.',
                  style: pw.TextStyle(font: fontBold, fontSize: 11),
                ),
              ),
              pw.Expanded(
                child: pw.RichText(
                  text: pw.TextSpan(
                    children: [
                      pw.TextSpan(
                        text: song.title,
                        style: pw.TextStyle(font: fontBold, fontSize: 11),
                      ),
                      if (song.artist.isNotEmpty)
                        pw.TextSpan(
                          text: '  —  ${song.artist}',
                          style: pw.TextStyle(
                            font: font,
                            fontSize: 11,
                            color: PdfColor.fromHex('757575'),
                          ),
                        ),
                    ],
                  ),
                ),
              ),
              if (meta.isNotEmpty)
                pw.Text(
                  meta,
                  style: pw.TextStyle(
                    font: fontBold,
                    fontSize: 10,
                    color: PdfColor.fromHex('E65100'),
                  ),
                ),
            ],
          ),
        ),
      );
    }
    return widgets;
  }
}
