import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../models/event_kit.dart';
import '../../models/lineup.dart';
import '../../models/section.dart';
import '../../models/setlist.dart';
import '../../models/setlist_break_type.dart';
import '../../models/song.dart';
import '../../utils/chordpro.dart';
import '../analytics_service.dart';

/// PDF layout for a setlist export.
/// [pack] = compact setlist page + every song as a one-page compact sheet
/// (#84; roster/stage map/schedule pages come later).
/// [performer] = one musician's copy: the full running order with only their
/// songs highlighted (needs `performerId`).
/// [cheatSheet] = ALL songs on one A4 page, two columns: key/scale, BPM,
/// time signature and the chord progression per section — the stage crib.
enum SetlistPdfLayout { detailed, compact, pack, eventGuide, performer, cheatSheet }

class PdfService {
  /// Hands the finished PDF to the platform.
  // ponytail: layoutPdf's web path drops `name` and clicks a target=_blank
  // anchor long after the tap — iOS Safari blocks it as a popup and returns
  // true, so the export silently does nothing. sharePdf's anchor carries
  // download=<name> and isn't blocked. Native keeps the print dialog.
  static Future<void> _output(Uint8List bytes, String name) => kIsWeb
      ? Printing.sharePdf(bytes: bytes, filename: name)
      : Printing.layoutPdf(onLayout: (_) async => bytes, name: name);

  /// Accented Latin letters -> ASCII, so a name survives filename sanitising.
  ///
  /// `[^\w\s-]` treats é as punctuation and deletes it outright, which turned
  /// "Roumé" into "Roum" and "André" into "Andr" in exported filenames. Dart has
  /// no Unicode normalisation in core, so map the Latin-1 range explicitly.
  static const _deaccent = {
    'à': 'a', 'á': 'a', 'â': 'a', 'ã': 'a', 'ä': 'a', 'å': 'a',
    'è': 'e', 'é': 'e', 'ê': 'e', 'ë': 'e',
    'ì': 'i', 'í': 'i', 'î': 'i', 'ï': 'i',
    'ò': 'o', 'ó': 'o', 'ô': 'o', 'õ': 'o', 'ö': 'o',
    'ù': 'u', 'ú': 'u', 'û': 'u', 'ü': 'u',
    'ç': 'c', 'ñ': 'n', 'ý': 'y', 'ÿ': 'y', 'ß': 'ss', 'æ': 'ae', 'ø': 'o',
  };

  /// Filename-safe title: drops anything a `download` attribute would choke on.
  static String _fileStem(String title) {
    final folded = title.split('').map((ch) {
      final lower = ch.toLowerCase();
      final mapped = _deaccent[lower];
      if (mapped == null) return ch;
      // Preserve the original case of the letter we replaced.
      return ch == lower ? mapped : mapped.toUpperCase();
    }).join();
    final cleaned = folded
        .trim()
        .replaceAll(RegExp(r'[^\w\s-]'), '')
        .trim()
        .replaceAll(RegExp(r'\s+'), '_');
    return cleaned.isEmpty ? 'flowgroove' : cleaned;
  }

  /// Exports a single song's performance sheet (chords over lyrics per section)
  /// to a shareable/printable PDF. [transpose] shifts the chords (display copy);
  /// sections without a ChordPro [Section.chordChart] fall back to their notes.
  /// When [fitOnePage] is true the whole sheet is scaled down onto a single
  /// A4 page (#79) instead of flowing across pages.
  static Future<void> exportSongSheet(
    String title,
    List<Section> sections, {
    int transpose = 0,
    String? songKey,
    int? bpm,
    int? timeTop,
    bool fitOnePage = false,
  }) async {
    unawaited(
      AnalyticsService.logPdfExported(itemType: 'song', itemCount: 1),
    );
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();
    final mono = await PdfGoogleFonts.robotoMonoRegular();
    final monoBold = await PdfGoogleFonts.robotoMonoBold();

    final blocks = _sheetBlocks(
      sections,
      transpose,
      font: font,
      fontBold: fontBold,
      mono: mono,
      monoBold: monoBold,
    );
    pw.Widget header() => _sheetHeader(
      title,
      sections,
      songKey: songKey,
      bpm: bpm,
      timeTop: timeTop,
      font: font,
      fontBold: fontBold,
    );

    final empty = pw.Text(
      'No lyrics or chords yet.',
      style: pw.TextStyle(font: font),
    );

    if (fitOnePage) {
      pdf.addPage(_onePageSheet(header(), blocks, empty));
    } else {
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(40),
          header: (context) => header(),
          footer: (context) => pw.Text(
            'Generated by FlowGroove · Page ${context.pageNumber}/${context.pagesCount}',
            style: pw.TextStyle(
              font: font,
              fontSize: 9,
              color: PdfColor.fromHex('757575'),
            ),
          ),
          build: (context) => blocks.isEmpty ? [empty] : blocks,
        ),
      );
    }

    await _output(await pdf.save(), '${_fileStem(title)}_sheet.pdf');
  }

  /// [performerId] is required by [SetlistPdfLayout.performer] and ignored by
  /// every other layout: it prints one musician's copy — the whole running
  /// order, with the songs they play highlighted.
  /// Builds the setlist PDF and hands it to the platform.
  ///
  /// A thin wrapper over [buildSetlistBytes] — the document build and the
  /// platform hand-off are separate so the layout can be produced (and tested,
  /// and written to a file) without a running app. `Printing.layoutPdf` /
  /// `sharePdf` need platform channels, which is why everything used to be
  /// unreachable from a test.
  static Future<void> exportSetlist(
    Setlist setlist,
    List<Song> songs, {
    SetlistPdfLayout layout = SetlistPdfLayout.detailed,
    String? performerId,
  }) async {
    unawaited(
      AnalyticsService.logSetlistExported(
        setlistId: setlist.id,
        format: layout.name,
        songCount: songs.length,
      ),
    );
    final bytes = await buildSetlistBytes(
      setlist,
      songs,
      layout: layout,
      performerId: performerId,
    );
    await _output(bytes, setlistFileName(setlist, layout, performerId, songs));
  }

  /// Filename the export would use, exposed so callers and tests agree on it.
  static String setlistFileName(
    Setlist setlist,
    SetlistPdfLayout layout,
    String? performerId,
    List<Song> songs,
  ) {
    final lineup = peopleById(setlist.eventKit?.people ?? const []);
    final performer = performerId == null ? null : lineup[performerId];
    final suffix = switch (layout) {
      SetlistPdfLayout.detailed => '',
      SetlistPdfLayout.compact => '_compact',
      SetlistPdfLayout.pack => '_pack',
      SetlistPdfLayout.eventGuide => '_event_guide',
      SetlistPdfLayout.performer => '_${_fileStem(performer?.name ?? 'part')}',
      SetlistPdfLayout.cheatSheet => '_cheatsheet',
    };
    return '${_fileStem(setlist.name)}_setlist$suffix.pdf';
  }

  /// The setlist PDF as bytes. No platform channels, so this is usable from a
  /// test or a CLI harness.
  static Future<Uint8List> buildSetlistBytes(
    Setlist setlist,
    List<Song> songs, {
    SetlistPdfLayout layout = SetlistPdfLayout.detailed,
    String? performerId,
  }) async {
    final pdf = pw.Document();

    // Load font that supports Cyrillic characters (Roboto)
    final font = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();

    final songById = {for (final s in songs) s.id: s};
    final items = setlist.effectiveItems;
    final lineup = peopleById(setlist.eventKit?.people ?? const []);
    final performer = performerId == null ? null : lineup[performerId];

    // Cheat sheet is its own single-page document — no MultiPage flow.
    if (layout == SetlistPdfLayout.cheatSheet) {
      pdf.addPage(_cheatSheetPage(setlist, items, songById, font, fontBold));
      return pdf.save();
    }

    final songWidgets =
        layout == SetlistPdfLayout.detailed ||
            layout == SetlistPdfLayout.eventGuide
        ? _detailedRows(items, songById, font, fontBold, lineup)
        : _compactRows(items, songById, font, fontBold, lineup, performerId);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        // The header runs on EVERY page, so only the title belongs here. The
        // description and venue are shown once, on page 1: a long description
        // (a whole running order pasted in, say) otherwise repeats on every
        // page and can crowd the songs down to a handful per sheet — which is
        // exactly what a real 18-song setlist did, turning a one-page export
        // into three.
        header: (context) {
          final firstPage = context.pageNumber == 1;
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                setlist.name,
                style: pw.TextStyle(font: fontBold, fontSize: firstPage ? 24 : 14),
              ),
              if (performer != null)
                pw.Text(
                  performer.role.isEmpty
                      ? performer.name
                      : '${performer.name} — ${performer.role}',
                  style: pw.TextStyle(font: fontBold, fontSize: firstPage ? 13 : 11),
                ),
              if (firstPage && setlist.description != null) ...[
                pw.SizedBox(height: 4),
                pw.Text(
                  setlist.description!,
                  style: pw.TextStyle(
                    font: font,
                    fontSize: 12,
                    color: PdfColor.fromHex('757575'),
                  ),
                ),
              ],
              if (firstPage && setlist.eventLocation != null) ...[
                pw.SizedBox(height: 8),
                pw.Row(
                  children: [
                    pw.Text(
                      // No emoji — the embedded font has no emoji glyphs.
                      'Venue: ${setlist.eventLocation}',
                      style: pw.TextStyle(font: font, fontSize: 10),
                    ),
                  ],
                ),
              ],
              pw.SizedBox(height: firstPage ? 20 : 8),
              pw.Divider(color: PdfColor.fromHex('E0E0E0')),
              pw.SizedBox(height: firstPage ? 20 : 8),
            ],
          );
        },
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              '${songs.length} songs',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColor.fromHex('757575'),
              ),
            ),
            pw.Text(
              'Generated by FlowGroove',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColor.fromHex('757575'),
              ),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColor.fromHex('757575'),
              ),
            ),
          ],
        ),
        build: (context) => [
          ...songWidgets,
          ..._lineupSection(items, lineup, font, fontBold),
        ],
      ),
    );

    // SetlistPack (#84): after the compact list, one compact sheet per song.
    if (layout == SetlistPdfLayout.pack) {
      final mono = await PdfGoogleFonts.robotoMonoRegular();
      final monoBold = await PdfGoogleFonts.robotoMonoBold();
      final empty = pw.Text(
        'No lyrics or chords yet.',
        style: pw.TextStyle(font: font),
      );
      for (final song in songs) {
        pdf.addPage(
          _onePageSheet(
            _sheetHeader(
              song.title,
              song.sections,
              songKey: song.ourKey,
              bpm: song.ourBPM,
              timeTop: song.accentBeats,
              font: font,
              fontBold: fontBold,
            ),
            _sheetBlocks(
              song.sections,
              0,
              font: font,
              fontBold: fontBold,
              mono: mono,
              monoBold: monoBold,
            ),
            empty,
          ),
        );
      }
    }

    // Event guide (#55): stage plot + role cards + rider after the setlist.
    if (layout == SetlistPdfLayout.eventGuide) {
      final kit = setlist.eventKit ?? const EventKit();
      pdf.addPage(_eventGuidePage(setlist, kit, font, fontBold));
    }

    return pdf.save();
  }

  /// One-page A4 sheet: header + section blocks scaled to fit (#79 layout).
  static pw.Page _onePageSheet(
    pw.Widget header,
    List<pw.Widget> blocks,
    pw.Widget empty,
  ) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      build: (context) => pw.FittedBox(
        alignment: pw.Alignment.topLeft,
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisSize: pw.MainAxisSize.min,
          children: [header, if (blocks.isEmpty) empty else ...blocks],
        ),
      ),
    );
  }

  /// Song-sheet header: title, key/BPM/time meta line, collapsed song map.
  static pw.Widget _sheetHeader(
    String title,
    List<Section> sections, {
    required String? songKey,
    required int? bpm,
    required int? timeTop,
    required pw.Font font,
    required pw.Font fontBold,
  }) {
    // Header metadata mirrors the song card: key + derived scale, tempo, time,
    // and the collapsed song map. All optional — omitted lines just don't render.
    final metaLine = <String>[
      if (songKey != null && songKey.trim().isNotEmpty)
        '${songKey.trim()} · ${keyToScale(songKey).quality}',
      if (bpm != null) '$bpm BPM',
      if (timeTop != null) '$timeTop/4',
    ].join('   ·   ');
    final songMap = sections.isNotEmpty
        ? songMapSummary(sections.map((s) => s.name).toList())
        : '';

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(title, style: pw.TextStyle(font: fontBold, fontSize: 22)),
        if (metaLine.isNotEmpty) ...[
          pw.SizedBox(height: 4),
          pw.Text(
            metaLine,
            style: pw.TextStyle(
              font: font,
              fontSize: 11,
              color: PdfColor.fromHex('616161'),
            ),
          ),
        ],
        if (songMap.isNotEmpty) ...[
          pw.SizedBox(height: 2),
          pw.Text(
            songMap,
            style: pw.TextStyle(
              font: font,
              fontSize: 10,
              color: PdfColor.fromHex('9E9E9E'),
            ),
          ),
        ],
        pw.SizedBox(height: 12),
        pw.Divider(color: PdfColor.fromHex('E0E0E0')),
        pw.SizedBox(height: 12),
      ],
    );
  }

  /// Per-section chords-over-lyrics blocks of a song sheet.
  static List<pw.Widget> _sheetBlocks(
    List<Section> sections,
    int transpose, {
    required pw.Font font,
    required pw.Font fontBold,
    required pw.Font mono,
    required pw.Font monoBold,
  }) {
    final orange = PdfColor.fromHex('E65100');
    final blocks = <pw.Widget>[];
    for (final section in sections) {
      final chart = section.chordChart?.trim() ?? '';
      if (chart.isEmpty && section.notes.trim().isEmpty) continue;

      blocks.add(
        pw.Text(
          section.name,
          style: pw.TextStyle(font: fontBold, fontSize: 14, color: orange),
        ),
      );
      blocks.add(pw.SizedBox(height: 4));

      if (chart.isNotEmpty) {
        for (final line in transposeChordChart(chart, transpose).split('\n')) {
          final co = chordsOverLyrics(line);
          if (co.chords.isNotEmpty) {
            blocks.add(
              pw.Text(
                co.chords,
                style: pw.TextStyle(
                  font: monoBold,
                  fontSize: 10,
                  color: orange,
                ),
              ),
            );
          }
          blocks.add(
            pw.Text(
              co.lyrics.isEmpty ? ' ' : co.lyrics,
              style: pw.TextStyle(font: mono, fontSize: 11),
            ),
          );
        }
      } else {
        blocks.add(
          pw.Text(section.notes, style: pw.TextStyle(font: font, fontSize: 11)),
        );
      }
      blocks.add(pw.SizedBox(height: 14));
    }
    return blocks;
  }

  /// Boxed card per song, one row each (original layout).
  static List<pw.Widget> _detailedRows(
    List<SetlistItem> items,
    Map<String, Song> songById,
    pw.Font font,
    pw.Font fontBold,
    Map<String, EventPerson> lineup,
  ) {
    final widgets = <pw.Widget>[];
    var n = 0; // per-section song number, reset by each break
    for (final item in items) {
      if (item.isBreak) {
        widgets.add(_breakDivider(item, fontBold));
        n = 0;
        continue;
      }
      final song = songById[item.songId];
      if (song == null) continue; // skip unavailable songs in export
      n++;
      widgets.add(
        pw.Container(
          margin: const pw.EdgeInsets.only(bottom: 12),
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColor.fromHex('E0E0E0')),
            borderRadius: pw.BorderRadius.circular(8),
          ),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                width: 30,
                height: 30,
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('E3F2FD'),
                  shape: pw.BoxShape.circle,
                ),
                child: pw.Center(
                  child: pw.Text(
                    '$n',
                    style: pw.TextStyle(
                      font: fontBold,
                      color: PdfColor.fromHex('0D47A1'),
                    ),
                  ),
                ),
              ),
              pw.SizedBox(width: 12),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      song.title,
                      style: pw.TextStyle(font: fontBold, fontSize: 14),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      song.artist,
                      style: pw.TextStyle(
                        font: font,
                        fontSize: 12,
                        color: PdfColor.fromHex('B0B0B0'),
                      ),
                    ),
                    if (performerLabel(item.performerIds, lineup)
                        case final who when who.isNotEmpty) ...[
                      pw.SizedBox(height: 4),
                      pw.Text(
                        who,
                        style: pw.TextStyle(
                          font: font,
                          fontSize: 10,
                          color: PdfColor.fromHex('616161'),
                        ),
                      ),
                    ],
                  ],
                ),
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  if (song.ourKey != null)
                    pw.Container(
                      padding: const pw.EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 4,
                      ),
                      decoration: pw.BoxDecoration(
                        color: PdfColor.fromHex('E8F5E9'),
                        borderRadius: pw.BorderRadius.circular(4),
                      ),
                      child: pw.Text(
                        song.ourKey!,
                        style: pw.TextStyle(
                          font: fontBold,
                          color: PdfColor.fromHex('1B5E20'),
                        ),
                      ),
                    ),
                  if (song.ourBPM != null) ...[
                    pw.SizedBox(height: 4),
                    pw.Text(
                      '${song.ourBPM} BPM',
                      style: pw.TextStyle(
                        font: fontBold,
                        fontSize: 12,
                        color: PdfColor.fromHex('E65100'),
                      ),
                    ),
                  ],
                ],
              ),
            ],
          ),
        ),
      );
    }
    return widgets;
  }

  /// "Who plays what" cheat sheet appended under the running order: one line
  /// per person with the song numbers they're on. Empty when nobody is
  /// assigned, so setlists without a lineup print exactly as before.
  static List<pw.Widget> _lineupSection(
    List<SetlistItem> items,
    Map<String, EventPerson> lineup,
    pw.Font font,
    pw.Font fontBold,
  ) {
    final byPerformer = songNumbersByPerformer(items);
    if (byPerformer.isEmpty) return const [];
    final rows = <pw.Widget>[];
    // Roster order, so the printed list matches the app's lineup.
    for (final person in lineup.values) {
      final numbers = byPerformer[person.id];
      if (numbers == null || numbers.isEmpty) continue;
      rows.add(
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 3),
          child: pw.Text(
            [
              person.name,
              if (person.role.isNotEmpty) person.role,
              numbers.map((n) => '#$n').join(', '),
            ].join('  —  '),
            style: pw.TextStyle(font: font, fontSize: 10),
          ),
        ),
      );
    }
    if (rows.isEmpty) return const [];
    return [
      pw.SizedBox(height: 16),
      pw.Divider(color: PdfColor.fromHex('E0E0E0')),
      pw.Text('Lineup', style: pw.TextStyle(font: fontBold, fontSize: 13)),
      pw.SizedBox(height: 6),
      ...rows,
    ];
  }

  /// A full-width section/break divider bar (matches a printed setlist).
  static pw.Widget _breakDivider(SetlistItem item, pw.Font fontBold) {
    final label = SetlistBreakType.labelFor(
      item.breakType,
      item.breakLabel,
    ).toUpperCase();
    return pw.Container(
      width: double.infinity,
      margin: const pw.EdgeInsets.only(top: 4, bottom: 12),
      padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 6),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('EEEEEE'),
        borderRadius: pw.BorderRadius.circular(4),
      ),
      child: pw.Text(
        label,
        style: pw.TextStyle(
          font: fontBold,
          fontSize: 11,
          color: PdfColor.fromHex('616161'),
        ),
      ),
    );
  }

  /// One dense line per song so a whole setlist fits on a single list.
  /// With [performerId] set this becomes that musician's copy: the whole
  /// running order stays (they need it to follow the show) but songs they
  /// don't play are greyed out.
  static List<pw.Widget> _compactRows(
    List<SetlistItem> items,
    Map<String, Song> songById,
    pw.Font font,
    pw.Font fontBold,
    Map<String, EventPerson> lineup, [
    String? performerId,
  ]) {
    final widgets = <pw.Widget>[];
    var n = 0; // per-section song number, reset by each break
    for (final item in items) {
      if (item.isBreak) {
        widgets.add(_breakDivider(item, fontBold));
        n = 0;
        continue;
      }
      final song = songById[item.songId];
      if (song == null) continue;
      n++;
      final mine =
          performerId == null || item.performerIds.contains(performerId);
      final dim = PdfColor.fromHex(mine ? '757575' : 'BDBDBD');
      final ink = mine ? PdfColors.black : PdfColor.fromHex('9E9E9E');
      final who = performerId == null
          ? performerLabel(item.performerIds, lineup)
          : '';
      final meta = <String>[
        if (song.ourKey != null) song.ourKey!,
        if (song.ourBPM != null) '${song.ourBPM} BPM',
      ].join('  ·  ');
      widgets.add(
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 3),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(
                width: 22,
                child: pw.Text(
                  '$n.',
                  style: pw.TextStyle(
                    font: fontBold,
                    fontSize: 11,
                    color: ink,
                  ),
                ),
              ),
              pw.Expanded(
                child: pw.RichText(
                  text: pw.TextSpan(
                    children: [
                      pw.TextSpan(
                        text: song.title,
                        style: pw.TextStyle(
                          font: mine ? fontBold : font,
                          fontSize: 11,
                          color: ink,
                        ),
                      ),
                      if (song.artist.isNotEmpty)
                        pw.TextSpan(
                          text: '  —  ${song.artist}',
                          style: pw.TextStyle(
                            font: font,
                            fontSize: 11,
                            color: dim,
                          ),
                        ),
                      if (who.isNotEmpty)
                        pw.TextSpan(
                          text: '   $who',
                          style: pw.TextStyle(
                            font: font,
                            fontSize: 9,
                            color: PdfColor.fromHex('616161'),
                          ),
                        ),
                    ],
                  ),
                ),
              ),
              if (meta.isNotEmpty)
                pw.Text(
                  meta,
                  style: pw.TextStyle(
                    font: fontBold,
                    fontSize: 10,
                    color: PdfColor.fromHex('E65100'),
                  ),
                ),
            ],
          ),
        ),
      );
    }
    return widgets;
  }

  /// The whole setlist on ONE A4 page, two columns, shrink-to-fit: per song
  /// its number, title/artist, key · scale · BPM · time signature, and the
  /// chord progression per section. Harmony comes from [Section.chordChart]
  /// (chord tokens only, consecutive repeats collapsed); a section without
  /// bracketed chords falls back to its free-text notes ("chord progressions"
  /// per the model docs). Key/BPM use the our→original fallback like the rest
  /// of the app — the other layouts print blanks without it.
  static pw.Page _cheatSheetPage(
    Setlist setlist,
    List<SetlistItem> items,
    Map<String, Song> songById,
    pw.Font font,
    pw.Font fontBold,
  ) {
    final blocks = _cheatSheetBlocks(items, songById, font, fontBold);
    // Two fixed-width columns; FittedBox scales the pair onto the page.
    final half = (blocks.length + 1) ~/ 2;
    pw.Widget column(List<pw.Widget> children) => pw.SizedBox(
      width: 300,
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        mainAxisSize: pw.MainAxisSize.min,
        children: children,
      ),
    );

    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      build: (context) => pw.FittedBox(
        alignment: pw.Alignment.topLeft,
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisSize: pw.MainAxisSize.min,
          children: [
            pw.Text(
              setlist.name,
              style: pw.TextStyle(font: fontBold, fontSize: 18),
            ),
            pw.SizedBox(height: 10),
            if (blocks.isEmpty)
              pw.Text('No songs yet.', style: pw.TextStyle(font: font))
            else
              pw.Row(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                mainAxisSize: pw.MainAxisSize.min,
                children: [
                  column(blocks.sublist(0, half)),
                  pw.SizedBox(width: 20),
                  column(blocks.sublist(half)),
                ],
              ),
          ],
        ),
      ),
    );
  }

  /// One compact block per song (plus break markers), in setlist order.
  static List<pw.Widget> _cheatSheetBlocks(
    List<SetlistItem> items,
    Map<String, Song> songById,
    pw.Font font,
    pw.Font fontBold,
  ) {
    final blocks = <pw.Widget>[];
    var n = 0; // per-section song number, reset by each break (as compact does)
    for (final item in items) {
      if (item.isBreak) {
        n = 0;
        blocks.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(top: 6, bottom: 4),
            child: pw.Text(
              SetlistBreakType.labelFor(
                item.breakType,
                item.breakLabel,
              ).toUpperCase(),
              style: pw.TextStyle(
                font: fontBold,
                fontSize: 9,
                color: PdfColor.fromHex('616161'),
              ),
            ),
          ),
        );
        continue;
      }
      final song = songById[item.songId];
      if (song == null) continue;
      n++;

      final key = (song.ourKey ?? song.originalKey)?.trim();
      final bpm = song.ourBPM ?? song.originalBPM;
      final meta = <String>[
        if (key != null && key.isNotEmpty) '$key · ${keyToScale(key).quality}',
        if (bpm != null) '$bpm BPM',
        '${song.accentBeats}/4',
      ].join('   ·   ');

      final progressionLines = <pw.Widget>[];
      for (final section in song.sections) {
        final chart = section.chordChart;
        var line = chart == null ? '' : chordProgression(chart).join(' | ');
        if (line.isEmpty) line = section.notes.trim();
        if (line.isEmpty) continue;
        progressionLines.add(
          pw.Padding(
            padding: const pw.EdgeInsets.only(left: 14, top: 1),
            child: pw.RichText(
              text: pw.TextSpan(
                children: [
                  if (section.name.trim().isNotEmpty)
                    pw.TextSpan(
                      text: '${section.name.trim()}:  ',
                      style: pw.TextStyle(
                        font: font,
                        fontSize: 8,
                        color: PdfColor.fromHex('757575'),
                      ),
                    ),
                  pw.TextSpan(
                    text: line,
                    style: pw.TextStyle(font: fontBold, fontSize: 8),
                  ),
                ],
              ),
            ),
          ),
        );
      }

      blocks.add(
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 6),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            mainAxisSize: pw.MainAxisSize.min,
            children: [
              pw.RichText(
                text: pw.TextSpan(
                  children: [
                    pw.TextSpan(
                      text: '$n. ${song.title}',
                      style: pw.TextStyle(font: fontBold, fontSize: 10),
                    ),
                    if (song.artist.trim().isNotEmpty)
                      pw.TextSpan(
                        text: ' — ${song.artist.trim()}',
                        style: pw.TextStyle(
                          font: font,
                          fontSize: 10,
                          color: PdfColor.fromHex('757575'),
                        ),
                      ),
                  ],
                ),
              ),
              pw.Padding(
                padding: const pw.EdgeInsets.only(left: 14),
                child: pw.Text(
                  meta,
                  style: pw.TextStyle(
                    font: fontBold,
                    fontSize: 8,
                    color: PdfColor.fromHex('E65100'),
                  ),
                ),
              ),
              ...progressionLines,
            ],
          ),
        ),
      );
    }
    return blocks;
  }

  /// Event-guide page (#55): stage plot (3×3 zone table), role cards and the
  /// rider checklist — the venue/crew handout after the setlist pages.
  static pw.Page _eventGuidePage(
    Setlist setlist,
    EventKit kit,
    pw.Font font,
    pw.Font fontBold,
  ) {
    pw.Widget zoneCell(String zoneId) {
      final placements = kit.stage[zoneId] ?? const <StagePlacement>[];
      return pw.Container(
        padding: const pw.EdgeInsets.all(6),
        constraints: const pw.BoxConstraints(minHeight: 54),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            for (final p in placements)
              pw.Text(
                // No emoji here — the embedded PDF font has no emoji glyphs.
                p.kind == 'member'
                    ? '• ${p.displayLabel}'
                    : '▪ ${p.displayLabel}',
                style: pw.TextStyle(font: font, fontSize: 9),
              ),
          ],
        ),
      );
    }

    final dateLine = [
      if (setlist.eventDateTime != null) setlist.formattedEventDate,
      if (setlist.eventLocation != null) setlist.eventLocation!,
    ].join(' · ');
    final songNumbers = songNumbersByPerformer(setlist.effectiveItems);

    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      build: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Event guide — ${setlist.name}',
            style: pw.TextStyle(font: fontBold, fontSize: 20),
          ),
          if (dateLine.isNotEmpty)
            pw.Text(dateLine, style: pw.TextStyle(font: font, fontSize: 11)),
          pw.SizedBox(height: 16),
          pw.Text(
            'Stage plot (top = back of stage)',
            style: pw.TextStyle(font: fontBold, fontSize: 13),
          ),
          pw.SizedBox(height: 6),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColor.fromHex('BDBDBD')),
            children: [
              for (var row = 0; row < 3; row++)
                pw.TableRow(
                  children: [
                    for (var col = 0; col < 3; col++)
                      zoneCell(stageZoneIds[row * 3 + col]),
                  ],
                ),
            ],
          ),
          pw.SizedBox(height: 2),
          pw.Center(
            child: pw.Text(
              'AUDIENCE',
              style: pw.TextStyle(
                font: font,
                fontSize: 8,
                color: PdfColor.fromHex('757575'),
              ),
            ),
          ),
          if (kit.people.isNotEmpty) ...[
            pw.SizedBox(height: 16),
            pw.Text(
              'Crew & guests',
              style: pw.TextStyle(font: fontBold, fontSize: 13),
            ),
            pw.SizedBox(height: 6),
            pw.Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                for (final p in kit.people)
                  pw.Container(
                    width: 160,
                    padding: const pw.EdgeInsets.all(8),
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(color: PdfColor.fromHex('BDBDBD')),
                      borderRadius: pw.BorderRadius.circular(4),
                    ),
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          p.name,
                          style: pw.TextStyle(font: fontBold, fontSize: 11),
                        ),
                        pw.Text(
                          p.role,
                          style: pw.TextStyle(font: font, fontSize: 9),
                        ),
                        if (songNumbers[p.id] case final numbers?
                            when numbers.isNotEmpty)
                          pw.Text(
                            'Songs: ${numbers.map((n) => '#$n').join(', ')}',
                            style: pw.TextStyle(font: font, fontSize: 9),
                          ),
                        if (p.notes != null)
                          pw.Text(
                            p.notes!,
                            style: pw.TextStyle(
                              font: font,
                              fontSize: 8,
                              color: PdfColor.fromHex('757575'),
                            ),
                          ),
                      ],
                    ),
                  ),
              ],
            ),
          ],
          if (kit.rider.isNotEmpty) ...[
            pw.SizedBox(height: 16),
            pw.Text(
              'Rider / equipment',
              style: pw.TextStyle(font: fontBold, fontSize: 13),
            ),
            pw.SizedBox(height: 6),
            for (final r in kit.rider)
              pw.Text(
                '${r.done ? '☑' : '☐'}  ${r.label}'
                '${r.qty != null ? '  ×${r.qty}' : ''}'
                '${r.notes != null ? '  — ${r.notes}' : ''}',
                style: pw.TextStyle(font: font, fontSize: 10),
              ),
          ],
          pw.Spacer(),
          pw.Text(
            'Generated by FlowGroove',
            style: pw.TextStyle(
              font: font,
              fontSize: 8,
              color: PdfColor.fromHex('9E9E9E'),
            ),
          ),
        ],
      ),
    );
  }
}
