import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

import '../../models/event_kit.dart';
import '../../models/section.dart';
import '../../models/setlist.dart';
import '../../models/song.dart';
import '../../utils/chordpro.dart';

/// PDF layout for a setlist export.
/// [pack] = compact setlist page + every song as a one-page compact sheet
/// (#84; roster/stage map/schedule pages come later).
enum SetlistPdfLayout { detailed, compact, pack, eventGuide }

class PdfService {
  /// Hands the finished PDF to the platform.
  // ponytail: layoutPdf's web path drops `name` and clicks a target=_blank
  // anchor long after the tap — iOS Safari blocks it as a popup and returns
  // true, so the export silently does nothing. sharePdf's anchor carries
  // download=<name> and isn't blocked. Native keeps the print dialog.
  static Future<void> _output(Uint8List bytes, String name) => kIsWeb
      ? Printing.sharePdf(bytes: bytes, filename: name)
      : Printing.layoutPdf(onLayout: (_) async => bytes, name: name);

  /// Filename-safe title: drops anything a `download` attribute would choke on.
  static String _fileStem(String title) {
    final cleaned = title
        .trim()
        .replaceAll(RegExp(r'[^\w\s-]'), '')
        .trim()
        .replaceAll(RegExp(r'\s+'), '_');
    return cleaned.isEmpty ? 'flowgroove' : cleaned;
  }

  /// Exports a single song's performance sheet (chords over lyrics per section)
  /// to a shareable/printable PDF. [transpose] shifts the chords (display copy);
  /// sections without a ChordPro [Section.chordChart] fall back to their notes.
  /// When [fitOnePage] is true the whole sheet is scaled down onto a single
  /// A4 page (#79) instead of flowing across pages.
  static Future<void> exportSongSheet(
    String title,
    List<Section> sections, {
    int transpose = 0,
    String? songKey,
    int? bpm,
    int? timeTop,
    bool fitOnePage = false,
  }) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();
    final mono = await PdfGoogleFonts.robotoMonoRegular();
    final monoBold = await PdfGoogleFonts.robotoMonoBold();

    final blocks = _sheetBlocks(
      sections,
      transpose,
      font: font,
      fontBold: fontBold,
      mono: mono,
      monoBold: monoBold,
    );
    pw.Widget header() => _sheetHeader(
      title,
      sections,
      songKey: songKey,
      bpm: bpm,
      timeTop: timeTop,
      font: font,
      fontBold: fontBold,
    );

    final empty = pw.Text(
      'No lyrics or chords yet.',
      style: pw.TextStyle(font: font),
    );

    if (fitOnePage) {
      pdf.addPage(_onePageSheet(header(), blocks, empty));
    } else {
      pdf.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.a4,
          margin: const pw.EdgeInsets.all(40),
          header: (context) => header(),
          footer: (context) => pw.Text(
            'Generated by FlowGroove · Page ${context.pageNumber}/${context.pagesCount}',
            style: pw.TextStyle(
              font: font,
              fontSize: 9,
              color: PdfColor.fromHex('757575'),
            ),
          ),
          build: (context) => blocks.isEmpty ? [empty] : blocks,
        ),
      );
    }

    await _output(await pdf.save(), '${_fileStem(title)}_sheet.pdf');
  }

  static Future<void> exportSetlist(
    Setlist setlist,
    List<Song> songs, {
    SetlistPdfLayout layout = SetlistPdfLayout.detailed,
  }) async {
    final pdf = pw.Document();

    // Load font that supports Cyrillic characters (Roboto)
    final font = await PdfGoogleFonts.robotoRegular();
    final fontBold = await PdfGoogleFonts.robotoBold();

    final songWidgets =
        layout == SetlistPdfLayout.detailed ||
            layout == SetlistPdfLayout.eventGuide
        ? _detailedRows(songs, font, fontBold)
        : _compactRows(songs, font, fontBold);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              setlist.name,
              style: pw.TextStyle(font: fontBold, fontSize: 24),
            ),
            if (setlist.description != null) ...[
              pw.SizedBox(height: 4),
              pw.Text(
                setlist.description!,
                style: pw.TextStyle(
                  font: font,
                  fontSize: 12,
                  color: PdfColor.fromHex('757575'),
                ),
              ),
            ],
            if (setlist.eventLocation != null) ...[
              pw.SizedBox(height: 8),
              pw.Row(
                children: [
                  pw.Text(
                    '📍 ${setlist.eventLocation}',
                    style: pw.TextStyle(font: font, fontSize: 10),
                  ),
                ],
              ),
            ],
            pw.SizedBox(height: 20),
            pw.Divider(color: PdfColor.fromHex('E0E0E0')),
            pw.SizedBox(height: 20),
          ],
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              '${songs.length} songs',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColor.fromHex('757575'),
              ),
            ),
            pw.Text(
              'Generated by FlowGroove',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColor.fromHex('757575'),
              ),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(
                font: font,
                fontSize: 10,
                color: PdfColor.fromHex('757575'),
              ),
            ),
          ],
        ),
        build: (context) => songWidgets,
      ),
    );

    // SetlistPack (#84): after the compact list, one compact sheet per song.
    if (layout == SetlistPdfLayout.pack) {
      final mono = await PdfGoogleFonts.robotoMonoRegular();
      final monoBold = await PdfGoogleFonts.robotoMonoBold();
      final empty = pw.Text(
        'No lyrics or chords yet.',
        style: pw.TextStyle(font: font),
      );
      for (final song in songs) {
        pdf.addPage(
          _onePageSheet(
            _sheetHeader(
              song.title,
              song.sections,
              songKey: song.ourKey,
              bpm: song.ourBPM,
              timeTop: song.accentBeats,
              font: font,
              fontBold: fontBold,
            ),
            _sheetBlocks(
              song.sections,
              0,
              font: font,
              fontBold: fontBold,
              mono: mono,
              monoBold: monoBold,
            ),
            empty,
          ),
        );
      }
    }

    // Event guide (#55): stage plot + role cards + rider after the setlist.
    if (layout == SetlistPdfLayout.eventGuide) {
      final kit = setlist.eventKit ?? const EventKit();
      pdf.addPage(_eventGuidePage(setlist, kit, font, fontBold));
    }

    final suffix = switch (layout) {
      SetlistPdfLayout.detailed => '',
      SetlistPdfLayout.compact => '_compact',
      SetlistPdfLayout.pack => '_pack',
      SetlistPdfLayout.eventGuide => '_event_guide',
    };
    await _output(
      await pdf.save(),
      '${_fileStem(setlist.name)}_setlist$suffix.pdf',
    );
  }

  /// One-page A4 sheet: header + section blocks scaled to fit (#79 layout).
  static pw.Page _onePageSheet(
    pw.Widget header,
    List<pw.Widget> blocks,
    pw.Widget empty,
  ) {
    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(32),
      build: (context) => pw.FittedBox(
        alignment: pw.Alignment.topLeft,
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          mainAxisSize: pw.MainAxisSize.min,
          children: [header, if (blocks.isEmpty) empty else ...blocks],
        ),
      ),
    );
  }

  /// Song-sheet header: title, key/BPM/time meta line, collapsed song map.
  static pw.Widget _sheetHeader(
    String title,
    List<Section> sections, {
    required String? songKey,
    required int? bpm,
    required int? timeTop,
    required pw.Font font,
    required pw.Font fontBold,
  }) {
    // Header metadata mirrors the song card: key + derived scale, tempo, time,
    // and the collapsed song map. All optional — omitted lines just don't render.
    final metaLine = <String>[
      if (songKey != null && songKey.trim().isNotEmpty)
        '${songKey.trim()} · ${keyToScale(songKey).quality}',
      if (bpm != null) '$bpm BPM',
      if (timeTop != null) '$timeTop/4',
    ].join('   ·   ');
    final songMap = sections.isNotEmpty
        ? songMapSummary(sections.map((s) => s.name).toList())
        : '';

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(title, style: pw.TextStyle(font: fontBold, fontSize: 22)),
        if (metaLine.isNotEmpty) ...[
          pw.SizedBox(height: 4),
          pw.Text(
            metaLine,
            style: pw.TextStyle(
              font: font,
              fontSize: 11,
              color: PdfColor.fromHex('616161'),
            ),
          ),
        ],
        if (songMap.isNotEmpty) ...[
          pw.SizedBox(height: 2),
          pw.Text(
            songMap,
            style: pw.TextStyle(
              font: font,
              fontSize: 10,
              color: PdfColor.fromHex('9E9E9E'),
            ),
          ),
        ],
        pw.SizedBox(height: 12),
        pw.Divider(color: PdfColor.fromHex('E0E0E0')),
        pw.SizedBox(height: 12),
      ],
    );
  }

  /// Per-section chords-over-lyrics blocks of a song sheet.
  static List<pw.Widget> _sheetBlocks(
    List<Section> sections,
    int transpose, {
    required pw.Font font,
    required pw.Font fontBold,
    required pw.Font mono,
    required pw.Font monoBold,
  }) {
    final orange = PdfColor.fromHex('E65100');
    final blocks = <pw.Widget>[];
    for (final section in sections) {
      final chart = section.chordChart?.trim() ?? '';
      if (chart.isEmpty && section.notes.trim().isEmpty) continue;

      blocks.add(
        pw.Text(
          section.name,
          style: pw.TextStyle(font: fontBold, fontSize: 14, color: orange),
        ),
      );
      blocks.add(pw.SizedBox(height: 4));

      if (chart.isNotEmpty) {
        for (final line in transposeChordChart(chart, transpose).split('\n')) {
          final co = chordsOverLyrics(line);
          if (co.chords.isNotEmpty) {
            blocks.add(
              pw.Text(
                co.chords,
                style: pw.TextStyle(
                  font: monoBold,
                  fontSize: 10,
                  color: orange,
                ),
              ),
            );
          }
          blocks.add(
            pw.Text(
              co.lyrics.isEmpty ? ' ' : co.lyrics,
              style: pw.TextStyle(font: mono, fontSize: 11),
            ),
          );
        }
      } else {
        blocks.add(
          pw.Text(section.notes, style: pw.TextStyle(font: font, fontSize: 11)),
        );
      }
      blocks.add(pw.SizedBox(height: 14));
    }
    return blocks;
  }

  /// Boxed card per song, one row each (original layout).
  static List<pw.Widget> _detailedRows(
    List<Song> songs,
    pw.Font font,
    pw.Font fontBold,
  ) {
    final widgets = <pw.Widget>[];
    for (int i = 0; i < songs.length; i++) {
      final song = songs[i];
      widgets.add(
        pw.Container(
          margin: const pw.EdgeInsets.only(bottom: 12),
          padding: const pw.EdgeInsets.all(12),
          decoration: pw.BoxDecoration(
            border: pw.Border.all(color: PdfColor.fromHex('E0E0E0')),
            borderRadius: pw.BorderRadius.circular(8),
          ),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                width: 30,
                height: 30,
                decoration: pw.BoxDecoration(
                  color: PdfColor.fromHex('E3F2FD'),
                  shape: pw.BoxShape.circle,
                ),
                child: pw.Center(
                  child: pw.Text(
                    '${i + 1}',
                    style: pw.TextStyle(
                      font: fontBold,
                      color: PdfColor.fromHex('0D47A1'),
                    ),
                  ),
                ),
              ),
              pw.SizedBox(width: 12),
              pw.Expanded(
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      song.title,
                      style: pw.TextStyle(font: fontBold, fontSize: 14),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      song.artist,
                      style: pw.TextStyle(
                        font: font,
                        fontSize: 12,
                        color: PdfColor.fromHex('B0B0B0'),
                      ),
                    ),
                  ],
                ),
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  if (song.ourKey != null)
                    pw.Container(
                      padding: const pw.EdgeInsets.symmetric(
                        horizontal: 8,
                        vertical: 4,
                      ),
                      decoration: pw.BoxDecoration(
                        color: PdfColor.fromHex('E8F5E9'),
                        borderRadius: pw.BorderRadius.circular(4),
                      ),
                      child: pw.Text(
                        song.ourKey!,
                        style: pw.TextStyle(
                          font: fontBold,
                          color: PdfColor.fromHex('1B5E20'),
                        ),
                      ),
                    ),
                  if (song.ourBPM != null) ...[
                    pw.SizedBox(height: 4),
                    pw.Text(
                      '${song.ourBPM} BPM',
                      style: pw.TextStyle(
                        font: fontBold,
                        fontSize: 12,
                        color: PdfColor.fromHex('E65100'),
                      ),
                    ),
                  ],
                ],
              ),
            ],
          ),
        ),
      );
    }
    return widgets;
  }

  /// One dense line per song so a whole setlist fits on a single list.
  static List<pw.Widget> _compactRows(
    List<Song> songs,
    pw.Font font,
    pw.Font fontBold,
  ) {
    final widgets = <pw.Widget>[];
    for (int i = 0; i < songs.length; i++) {
      final song = songs[i];
      final meta = <String>[
        if (song.ourKey != null) song.ourKey!,
        if (song.ourBPM != null) '${song.ourBPM} BPM',
      ].join('  ·  ');
      widgets.add(
        pw.Padding(
          padding: const pw.EdgeInsets.symmetric(vertical: 3),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.SizedBox(
                width: 22,
                child: pw.Text(
                  '${i + 1}.',
                  style: pw.TextStyle(font: fontBold, fontSize: 11),
                ),
              ),
              pw.Expanded(
                child: pw.RichText(
                  text: pw.TextSpan(
                    children: [
                      pw.TextSpan(
                        text: song.title,
                        style: pw.TextStyle(font: fontBold, fontSize: 11),
                      ),
                      if (song.artist.isNotEmpty)
                        pw.TextSpan(
                          text: '  —  ${song.artist}',
                          style: pw.TextStyle(
                            font: font,
                            fontSize: 11,
                            color: PdfColor.fromHex('757575'),
                          ),
                        ),
                    ],
                  ),
                ),
              ),
              if (meta.isNotEmpty)
                pw.Text(
                  meta,
                  style: pw.TextStyle(
                    font: fontBold,
                    fontSize: 10,
                    color: PdfColor.fromHex('E65100'),
                  ),
                ),
            ],
          ),
        ),
      );
    }
    return widgets;
  }

  /// Event-guide page (#55): stage plot (3×3 zone table), role cards and the
  /// rider checklist — the venue/crew handout after the setlist pages.
  static pw.Page _eventGuidePage(
    Setlist setlist,
    EventKit kit,
    pw.Font font,
    pw.Font fontBold,
  ) {
    pw.Widget zoneCell(String zoneId) {
      final placements = kit.stage[zoneId] ?? const <StagePlacement>[];
      return pw.Container(
        padding: const pw.EdgeInsets.all(6),
        constraints: const pw.BoxConstraints(minHeight: 54),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            for (final p in placements)
              pw.Text(
                // No emoji here — the embedded PDF font has no emoji glyphs.
                p.kind == 'member'
                    ? '• ${p.displayLabel}'
                    : '▪ ${p.displayLabel}',
                style: pw.TextStyle(font: font, fontSize: 9),
              ),
          ],
        ),
      );
    }

    final dateLine = [
      if (setlist.eventDateTime != null) setlist.formattedEventDate,
      if (setlist.eventLocation != null) setlist.eventLocation!,
    ].join(' · ');

    return pw.Page(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(40),
      build: (context) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'Event guide — ${setlist.name}',
            style: pw.TextStyle(font: fontBold, fontSize: 20),
          ),
          if (dateLine.isNotEmpty)
            pw.Text(dateLine, style: pw.TextStyle(font: font, fontSize: 11)),
          pw.SizedBox(height: 16),
          pw.Text(
            'Stage plot (top = back of stage)',
            style: pw.TextStyle(font: fontBold, fontSize: 13),
          ),
          pw.SizedBox(height: 6),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColor.fromHex('BDBDBD')),
            children: [
              for (var row = 0; row < 3; row++)
                pw.TableRow(
                  children: [
                    for (var col = 0; col < 3; col++)
                      zoneCell(stageZoneIds[row * 3 + col]),
                  ],
                ),
            ],
          ),
          pw.SizedBox(height: 2),
          pw.Center(
            child: pw.Text(
              'AUDIENCE',
              style: pw.TextStyle(
                font: font,
                fontSize: 8,
                color: PdfColor.fromHex('757575'),
              ),
            ),
          ),
          if (kit.people.isNotEmpty) ...[
            pw.SizedBox(height: 16),
            pw.Text(
              'Crew & guests',
              style: pw.TextStyle(font: fontBold, fontSize: 13),
            ),
            pw.SizedBox(height: 6),
            pw.Wrap(
              spacing: 8,
              runSpacing: 8,
              children: [
                for (final p in kit.people)
                  pw.Container(
                    width: 160,
                    padding: const pw.EdgeInsets.all(8),
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(color: PdfColor.fromHex('BDBDBD')),
                      borderRadius: pw.BorderRadius.circular(4),
                    ),
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          p.name,
                          style: pw.TextStyle(font: fontBold, fontSize: 11),
                        ),
                        pw.Text(
                          p.role,
                          style: pw.TextStyle(font: font, fontSize: 9),
                        ),
                        if (p.notes != null)
                          pw.Text(
                            p.notes!,
                            style: pw.TextStyle(
                              font: font,
                              fontSize: 8,
                              color: PdfColor.fromHex('757575'),
                            ),
                          ),
                      ],
                    ),
                  ),
              ],
            ),
          ],
          if (kit.rider.isNotEmpty) ...[
            pw.SizedBox(height: 16),
            pw.Text(
              'Rider / equipment',
              style: pw.TextStyle(font: fontBold, fontSize: 13),
            ),
            pw.SizedBox(height: 6),
            for (final r in kit.rider)
              pw.Text(
                '${r.done ? '☑' : '☐'}  ${r.label}'
                '${r.qty != null ? '  ×${r.qty}' : ''}'
                '${r.notes != null ? '  — ${r.notes}' : ''}',
                style: pw.TextStyle(font: font, fontSize: 10),
              ),
          ],
          pw.Spacer(),
          pw.Text(
            'Generated by FlowGroove',
            style: pw.TextStyle(
              font: font,
              fontSize: 8,
              color: PdfColor.fromHex('9E9E9E'),
            ),
          ),
        ],
      ),
    );
  }
}
